extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    verbosity: normal
  prometheus:
    endpoint: "0.0.0.0:49152"
  otlp:
    endpoint: 0.0.0.0:4217
    tls:
      insecure: true

service:
#  telemetry:
#    logs:
#      level: "debug"
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus, logging ]
    traces:
      receivers: [ otlp ]
      processors: [  ]
      exporters: [ otlp, logging ]

  extensions: [ health_check, pprof, zpages ]