package org.jboss.eap.qe.microprofile.openapi.model;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.microprofile.openapi.OASFactory;
import org.eclipse.microprofile.openapi.OASModelReader;
import org.eclipse.microprofile.openapi.models.ExternalDocumentation;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.info.Contact;
import org.eclipse.microprofile.openapi.models.info.Info;
import org.eclipse.microprofile.openapi.models.info.License;

/**
 * Generates a base model to be used by the OpenAPI.
 */
public class AnotherOpenApiModelReader implements OASModelReader {
    /**
     * Creates a new {@link Info} instance, modifying the output OpenAPI document in order to add local router
     * information
     *
     * @return A new {@link OpenAPI} instance that will serve as base for generation
     */
    @Override
    public OpenAPI buildModel() {
        OpenAPI api = OASFactory.createObject(OpenAPI.class);
        // .info
        Info info = OASFactory.createInfo();
        // .info.title
        final String newTitle = ((info.getTitle() == null) || info.getTitle().isEmpty() ? ""
                : info.getTitle()) +
                String.format("[LSR Application @ %s]", AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        info.setTitle(newTitle);
        // .info.description
        final String newDescription = ((info.getDescription() == null) || (info.getDescription().isEmpty()) ? ""
                : info.getDescription()) +
                String.format("[Generated by router: %s]", AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        info.setDescription(newDescription);
        // .info.termsOfService
        final String newTermsOfService = ((info.getTermsOfService() == null) || (info.getTermsOfService().isEmpty()) ? ""
                : info.getTermsOfService()) +
                String.format("Terms of Service: refer to %s", AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        info.setTermsOfService(newTermsOfService);
        // .info.contact
        info.setContact(new AnotherContact());
        // .info.license
        info.setLicense(new AnotherLicense());
        // .info.version
        final String newVersion = ((info.getVersion() == null) || (info.getVersion().isEmpty()) ? "0.0.1"
                : info.getVersion()) +
                String.format(".%s", AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        info.setVersion(newVersion);
        // .info.summary
        final String newSummary = ((info.getSummary() == null) || (info.getSummary().isEmpty()) ? ""
                : info.getSummary()) +
                String.format("A Service provider router exposed by %s", AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        info.setSummary(newSummary);
        api.setInfo(info);
        // .externalDocs
        ExternalDocumentation externalDocumentation = OASFactory.createExternalDocumentation();
        externalDocumentation.setUrl("http://another-oas-model-reader-based-external-docs.org");
        externalDocumentation.setDescription("Could be overridden by static files and/or annotations");
        api.setExternalDocs(externalDocumentation);
        return api;
    }

    public static class AnotherContact implements Contact {

        private String name;
        private String url;
        private String email;
        private final Map<String, Object> extensions = new HashMap<>();

        public AnotherContact() {
            this("Admin_" + AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN,
                    "https://" + AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN,
                    "admin@" + AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        }

        public AnotherContact(String name, String url, String email) {
            this.name = name;
            this.url = url;
            this.email = email;
        }

        @Override
        public String getName() {
            return this.name;
        }

        @Override
        public void setName(String name) {
            this.name = name;
        }

        @Override
        public String getUrl() {
            return this.url;
        }

        @Override
        public void setUrl(String url) {
            this.url = url;
        }

        @Override
        public String getEmail() {
            return this.email;
        }

        @Override
        public void setEmail(String email) {
            this.email = email;
        }

        @Override
        public Map<String, Object> getExtensions() {
            return this.extensions;
        }

        @Override
        public Contact addExtension(String name, Object value) {
            this.extensions.put(name, value);
            return this;
        }

        @Override
        public void removeExtension(String name) {
            this.extensions.remove(name);
        }

        @Override
        public void setExtensions(Map<String, Object> extensions) {
            this.extensions.clear();
            this.extensions.putAll(extensions);
        }
    }

    public static class AnotherLicense implements License {

        private String name;
        private String url;
        private String identifier;
        private final Map<String, Object> extensions = new HashMap<>();

        public AnotherLicense() {
            this(AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN + " license",
                    "https://" + AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN,
                    "license_" + AnotherOpenApiFilter.ANOTEHR_LOCAL_TEST_ROUTER_FQDN);
        }

        public AnotherLicense(String name, String url, String identifier) {
            this.name = name;
            this.url = url;
            this.identifier = identifier;
        }

        @Override
        public String getName() {
            return this.name;
        }

        @Override
        public void setName(String name) {
            this.name = name;
        }

        @Override
        public String getUrl() {
            return this.url;
        }

        @Override
        public void setUrl(String url) {
            this.url = url;
        }

        @Override
        public String getIdentifier() {
            return this.identifier;
        }

        @Override
        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }

        @Override
        public Map<String, Object> getExtensions() {
            return this.extensions;
        }

        @Override
        public License addExtension(String name, Object value) {
            this.extensions.put(name, value);
            return this;
        }

        @Override
        public void removeExtension(String name) {
            this.extensions.remove(name);
        }

        @Override
        public void setExtensions(Map<String, Object> extensions) {
            this.extensions.clear();
            this.extensions.putAll(extensions);
        }
    }
}
